apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - UK          
  containers:
  - name: webapp
    image: vimal13/apache-webserver-php 
    imagePullPolicy: IfNotPresent
