apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    role: myrole
  name: static-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: myrole
  type: NodePort
status:
  loadBalancer: {}
