apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: vimal13/apache-webserver-php 
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
