apiVersion: v1
kind: Pod
metadata:
  name: "mydb"
  labels: 
    app: mydb 
spec:
  containers:
  - name: "mydb"       
    image: mysql:5.7
    env:
    - name: MYSQL_DATABASE
      value: "myworddb"
    - name: MYSQL_USER
      value: "abdhesh"
    - name: MYSQL_ROOT_PASSWORD 
      valueFrom: 
        secretKeyRef: 
          name: mysecret 
          key: mysql_root_pass   

    - name: MYSQL_PASSWORD 
      valueFrom: 
        secretKeyRef: 
          name: mysecret 
          key: mysql_pass



