apiVersion: v1
kind: Pod
metadata:
  name: "mywordpres"
  labels: 
    app: mywordpres 
spec:
  containers:
  - name: "mywp"       
    image: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value:  "mysql-headless-svc"     
    - name: WORDPRESS_DB_NAME
      value: "myworddb"
    - name: WORDPRESS_DB_USER
      value: "abdhesh"
    - name: WORDPRESS_DB_PASSWORD
      valueFrom: 
        secretKeyRef: 
          name: wpsecret 
          key: wp_db_pass  

